name: KitPvP
version: 1.0.0
main: com.crystalox.kitpvp.KitPvPPlugin
api-version: '1.16'
softdepend: [EconomyPlus]

commands:
  kit:
    description: Выдать себе кит
    usage: /kit [название]
  kits:
    description: Показать все доступные киты
    usage: /kits
  stats:
    description: Посмотреть статистику игрока
    usage: /stats [игрок]
  top:
    description: '&7Топ игроков по убийствам'
    usage: /top
    permission: crystalox.kitpvp.command.top
  kitpvp:
    description: Админ-команды KitPvP
    usage: /kitpvp <pos1|pos2|savearena|setspawn|reload>

permissions:
  crystalox.kitpvp.admin:
    description: Доступ к админ-командам KitPvP
    default: op
  crystalox.kitpvp.command.kit:
    description: Разрешает использовать команду kit
    default: true
  crystalox.kitpvp.command.stats:
    description: Разрешает использовать команду stats
    default: true
  crystalox.kitpvp.command.top:
    description: Разрешает использовать команду top
    default: true
